In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage.feature import blob_dog, blob_log, blob_doh

img = cv2.imread('stupidline.jpg', cv2.IMREAD_GRAYSCALE)
blobs_doh = blob_doh(img, max_sigma=30, min_sigma=20, threshold=.01, num_sigma=10)
print("Dit zijn je blobs (y, x, sigma):\n", blobs_doh)
print("Eentje wordt niet gevonden? Misschien na binarizen")
# Parameters tweaken

Dit zijn je blobs (y, x, sigma):
 [[284. 125.  20.]
 [236. 241.  30.]
 [119. 108.  30.]
 [ 38. 193.  30.]]
Eentje wordt niet gevonden? Misschien na binarizen
